spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8080
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-atguigu-dev
---
server: 
  port: 8081
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-atguigu-test