---
server: 
  port: 8085
spring:
  profiles: dev     #开发环境
  application: 
    name: spring-cloud-config-dev
---
server: 
  port: 8081
spring:
  profiles: test   #测试环境
  application: 
    name: spring-cloud-config-test